Perforated peptic ulcer
Perforated gastric carcinoma
Acute gastritis
Irritant poisons
Small bowel obstruction
Constipation
Regional ileitis
Intussusception
Sigmoid volvulus
Acute colonic diverticulitis
Large bowel obstruction
Strangulated hernia
Acute mesenteric occlusion
Inflammatory bowel syndrome
Acute appendicitis
Acute pancreatitis
Recurrent pancreatitis
Pancreatic trauma
Gallstone
Cbd stone
Acute cholecystitis
Acute cholangitis
Biliary disease
Liver trauma
Acute hepatitis
Liver malignancy
Splenic trauma
Spontaneous rupture of spleen
Splenic infarction
Renal calculus
Ureteric calculus
Vesical calculus
Renal trauma
Pyelonephritis
Pyonephrosis
Renal colic
Salpingitis
Pyosalpinx
Ectopic pregnancy
Torsion of fibroid
Degenaration of fibroid
Twisted ovarian cyst
Ruptured ovarian cyst
Pelvic inflammatory disease
Pregnancy
Pre-eclampsia
Ruptured abdominal aortic aneurysm
Dissecting abdominal aortic aneurysm
Herpes zoster
Myocardial infarction
Acute pericarditis
Acute diaphragmatic pleurisy
Diabetic ketoacidosis
