Perforated peptic ulcer
Acute cholecystitis
Rupture of gallbladder
Acute pancreatitis
Strangulated hernia
Intestinal perforation
Mesenteric thrombosis
Mesenteric embolism
Meckel's diverticulitis
Acute ileitis
Appendicitis
Volvulitis
Perforated diverticulitis
Infective peritonitis
Twisted ovarian cyst
Ruptured ectopic pregnancy
Acute salpingitis
Torsion of fibroid
Degeneration of fibroid
Perforation of uterus
Perforation of vagina
Rupture of spleen
Rupture of liver
Ruptured abdominal aortic aneurysm
