Aplastic anemia
Myelodysplasia
Myelofibrosis
Leukemia
Lymphoma
Lymphoproliferative disorders
Hypersplenism
Vitamin b12 deficiency
Acute alcohol intoxication
Tuberculosis
Sarcoidosis
Lupus erythematosus
Sepsis
Disemminated intravascular coagulation
Hiv
Thrombotic thrombocytopenic purpura
Hemolytic uremic syndrome
Hellp syndrome
Antiphospholipid syndrome
Drug intoxication
Lead toxicity
Copper toxicity
Zinc toxicity
Iron deficiency
Thalassemia
Endocrinopathy
Monoclonal gammopathy
Iron deficiency anemia
Common variable immunodeficiency
Iron deficiency anemia
Vitamin b12 deficiency
Vitamin b1 deficiency
