Cauda equina
Spinal cord trauma
Osteomyelitis
Cns tumor
Cns infection
Spinal fracture
Hernia
Urinary tract infection
Immunosupression
Injection drugs use
Corticosteroids
Sciatica
Compression fracture
Cancer
Pancreatitis
Kidney stones
Renal disease
Abdominal aortic aneurysm
Ankylosing spondylitis
Rheumatoid arthritis
Lupus erythematosus
Lumbar reticulopathy
Spinal stenosis
Multiple myeloma
Lymphoma
Leukemia
Osteomyelitis
Septic diskitis
Paraspinal abscess
Epidural abscess
Psoriatic arthritis
Reactive arthritis
Rheumatoid arthritis
Prostatitis
Endometriosis
Pelvic inflammatory disease
Nephrolithiasis
Pyelonephritis
Perinephric abscess
Pancreatitis
Cholecystitis
Penetrating ulcer
Pregnancy
Osteoporosis
