Trauma
Tissue injury
Tissue abnormality
Thrombocytopenia
Bone marrow disease
Bone marrow malignancy
Alcohol
Vitamin b12 deficiency
Splenic sequestration
Autoimmune thrombocytopenia
Idiopathic thrombocytopenic purpura
Aids
Lupus erythematosus
Multiple myeloma
Lymphoma
Leukemia
Anticoagulation medication use
Carbamazepine use
Sulfonamides use
Lymphoproliferative disorders
Disseminated intravascular coagulation
Thrombotic thrombocytopenic purpura
Sepsis
Von willebrand disease
Hereditary bleeding disorders
Nsaid use
Myeloproliferative disorders
Essential thrombocythemia
Polycythemia vera
Hemophilia a
Liver disease
Vitamin k deficiency
