Dementia
Dehydration
Hypoglycemia
Hyperglycemia
Acidosis
Alkalosis
Liver disease
Hypoxia
Dehydration
Thyroid disease
Uremia
Thiamine deficiency
Infection
Cns infection
Transient ischemic attack
Stroke
Vasculitis
Cns tumor
Subdural hematoma
Myocardial infarction
Heart failure
Arrythmia
Alcohol withdrawal
Narcotics withdrawal
Anticholinergics
Diuretics
Prion disease
Syphilis
Vitamin b12 deficiency
Opioids
Corticosteroids
Antidepressants
Anxiolytics
Fecal impaction
Urinary retention
Sensory deprivation
Severe illness
Pneumonia
Aspiration pneumonia
Eclampsia
Rhabdomyolysis
