Dementia
Dehydration
Hypoglycemia
Hyperglycemia
Acidosis
Alkalosis
Liver disease
Hypoxia
Dehydration
Thyroid disease
Uremia
Thiamine deficiency
Infection
Cns infection
Ischemic stroke
Hemorrhagic stroke
Vasculitis
Cns tumour
Subdural hematoma
Myocardial infarction
Heart failure
Arrythmia
Alcohol withdrawal
Narcotics withdrawal
Anticholinergics
Diuretics
Prion disease
Syphilis
B12 deficiency
Opioids
Corticosteroids
Antidepressants
Anxiolytics
Fecal impaction
Urinary retention
Sensory deprivation
Severe illness
