Heart failure
Asthma
Anxiety
Pneumonia
Acute upper airway obstruction
Hypersensitivity reaction
Bronchospasm
Respiratory tract infection
Goodpastures
Haemolytic anemia
Autoimmune-mediated haemolytic anemia
Atrial fibrillation
Anemia
Blood loss
Carbon monoxide toxicity
Hypotension
Pulmonary embolism
Collapsed lung
Hiatal hernia
Obesity
Interstitial pulmonary fibrosis
Goodpastures
Sarcoidosis
Amyloidosis
Iron deficiency anemia
Hypothyroidism
