Heart failure
Kidney disease
Chronic kidney disease
Nephrotic syndrome
Hypoalbuminemia
Monoamine oxidase inhibitor use
Antihypertensives
Synthetic hormone use
Nsaids
Thiazolidinedione use
Myxedema
Venous obstruction
Venous insufficiency
Lymphatic obstruction
Deep vein thrombosis
Lymphedema
Cellulitis
Cirrhosis
Liver disease
Ovarian cancer
Hypersensitivity reaction
Goodpastures
Amyloidosis
Pregnancy
Pre eclampsia
Complement deficiency
Acromegaly
Vitamin b1 deficiency
