Severe combined immunodeficiency
Poverty
Poor nutrition
Child neglect
Gastroesophageal reflux disease
Pyloric stenosis
Lactose intolerance
Coeliac disease
Short bowel syndrome
Cystic fibrosis
Biliary atresia
Hyperthyroidism
Chronic infections
Tuberculosis
Hiv
Torch infection
Inflammatory bowel disease
Diabetes mellitus
Congenital heart defect
Bronchopulmonary dysplasia
Bronchiectasis
Galactosemia
Glycogen storage diseases
Digeorge syndrome
