Hemolytic anemia
Liver disease
Cirrhosis
G6pd deficiency
Sickle-cell anemia
Spherocytosis
Thalassemia
Pyruvate kinase deficiency
Hemolytic anemia
Hemolytic-uremic syndrome
Malaria
Acute hepatitis
Chronic hepatitis
Hepatotoxicity
Drug-induced hepatitis
Alcoholic liver disease
Gilbert's syndrome
Crigler-najjar syndrome
Crigler-najjar syndrome
Leptospirosis
Choledocholithiasis
Pancreatic cancer of the pancreatic head
Biliary tract strictures
Biliary atresia
Primary biliary cholangitis
Cholestasis of pregnancy
Pancreatitis
Pancreatitis
Mirizzi's syndrome
Parasitic infection
Parasitic infection
Scurvy
