Lupus erythematosus
Hyperglycemia
Diabetes mellitus
Chronic kidney failure
Porphyria
Amyloidosis
Liver failure
Hypothyroidism
Heavy metal toxicity
Guillain barre syndrome
Leprosy
Multiple sclerosis
Sjogren's syndrome
Babesiosis
Lyme disease
Vasculitis
Sarcoidosis
Aids
Cns tumor
Monoclonal gammopathy
Vitamin b12 deficiency
Vitamin a deficiency
Vitamin e deficiency
Vitamin b1 deficiency
Fluoroquinolone use
Vasculitis
Leprosy
