Food allergy
Food poisoning
Adrenal insufficiency
Nerve agent toxicity
Excessive eating
Alcohol use
Opioid use
Ssri use
Chemotherapy drugs
Viral gastroenteritis
Gallstones
Constipation
Gastritis
Celiac disease
Bowel obstruction
Acute abdomen
Peritonitis
Ileus
Lactose intolerance
Influenza
Aids
Parasitic infection
Malaria
Pheochromocytoma
Brain tumor
Hypercalcemia
Uremia
Hypoglycemia
Hyperglycemia
Motion sickness
Menieres disease
Migraine
Hydrocephalus
Cerebral hemorrhage
Benign intracranial hypertension
Pregnancy
Bulimia nervosa
Purging disorder
Eating disorders
Intense emotions
Anxiety
Panic disorder
Kidney failure
Rhabdomyolysis
Aspiration pneumonia
Mallory-weiss tear
Coughing fits
Concussion
